index_frontEnd:
    pattern: /
    defaults: { _controller: FrontEndBundle:Index:index }
    
login_ajax:
  pattern: /login
  defaults: { _controller: FrontEndBundle:Login:login }
  
logout:
  pattern: /logout
  defaults: { _controller: FrontEndBundle:Login:logout }

register:
  pattern: /register
  defaults: { _controller: FrontEndBundle:Register:register }
<<<<<<< HEAD
  
search_ajax:
  pattern: /search
  defaults: { _controller: FrontEndBundle:Search:search }

search:
    pattern: /search
    defaults: { _controller: FrontEndBundle:Search:search }
=======

search:
    pattern: /searchFilter
    defaults: { _controller: FrontEndBundle:Search:filter }
>>>>>>> origin/akshat
